#!/bin/sh

bl_dev=/sys/class/backlight/intel_backlight
max=`cat ${bl_dev}/max_brightness`
current=`cat ${bl_dev}/brightness`
min=1

step=$(($max/5))

op=${1}
[ "${op}" != "-" ] && [ "${op}" != "+" ] && op="+"

new=$(($current $op $step))

if [ $new -lt $min ]
then
    echo $min > $bl_dev/brightness
elif [ $new -gt $max ]
then
    echo $max > $bl_dev/brightness
else
    echo $new > $bl_dev/brightness
fi
